const styles = (theme) => ({
  root: {
    backgroundColor: "#8B8B8B",
    height: "calc(100% - 35px)",
    position: "absolute",
    left: "0",
    width: "12rem",
    boxShadow: "0px 0px 2px black",
  },
  newChatBtn: {
    borderRadius: "0px",
  },
  unreadMessage: {
    color: "red",
    position: "absolute",
    top: "0",
    right: "5px",
  },
  newNoteBtn: {
    width: "100%",
    height: "35px",
    paddingTop: "2rem",
    paddingBottom: "2rem",
    borderRadius: "0px",
    backgroundColor: "#8B8B8B",
    fontSize: 18,
    color: "#FFF4E3",
    "&:hover": {
      backgroundColor: "#FFF4E3",
      color: "#8B8B8B",
    },
    //position: "absolute",
    bottom: "0rem",
  },
  notebookMenuButton: {
    width: "100%",
    height: "35px",
    paddingTop: "2rem",
    paddingBottom: "2rem",
    borderRadius: "0px",
    backgroundColor: "#8B8B8B",
    fontSize: 18,
    color: "#FFF4E3",
    "&:hover": {
      backgroundColor: "#FFF4E3",
      color: "#8B8B8B",
    },
    //position: "absolute",
    bottom: "0rem",
  },
  openMenu: {
    width: "100%",
    height: "2rem",
    borderRadius: "0px",
    paddingTop: "1rem",
    paddingBottom: "1rem",
    backgroundColor: "#FFF4E3",
    fontSize: 18,
    color: "#8B8B8B",
    "&:hover": {
      backgroundColor: "#8B8B8B",
      color: "#FFF4E3",
    },
  },
  closeMenu: {
    width: "100%",
    height: "2rem",
    borderRadius: "0px",
    backgroundColor: "#8B8B8B",
    paddingTop: "1rem",
    paddingBottom: "1rem",
    fontSize: 18,
    color: "#FFF4E3",
    "&:hover": {
      backgroundColor: "#FFF4E3",
      color: "#8B8B8B",
    },
  },
  sidebarContainer1: {
    marginTop: "0px",
    width: "18rem",
    height: "100%",
    boxSizing: "border-box",
    float: "left",
    backgroundColor: "#8B8B8B",
    // overflowY: "scroll",
    // overflowX: "hidden",
    position: "absolute",
    flex: 1,
    margin: 0,
    zIndex: 1,
  },
  sidebarContainer2: {
    marginTop: "0px",
    width: "6rem",
    height: "100%",
    boxSizing: "border-box",
    float: "left",
    backgroundColor: "#FFF4E3",
    // overflowY: "scroll",
    // overflowX: "hidden",
    position: "absolute",
    flex: 1,
    margin: 0,
    zIndex: 1,
  },
  newNoteInput: {
    width: "100%",
    margin: "0px",
    height: "35px",
    outline: "none",
    border: "none",
    paddingLeft: "5px",
    "&:focus": {
      outline: "2px solid rgba(81, 203, 238, 1)",
    },
  },
  newNoteSubmitBtn: {
    width: "100%",
    backgroundColor: "#28787c",
    borderRadius: "30px",
    color: "white",
  },
});

export default styles;
